### ISSUE TITLE
Error handling in data model module

### ISSUE THREAD

**Issue by djs0109** [N5GEH/n5geh.tools.entirety#173]
We should improve the robustness of the data model module. If the data model is not "FIWARE comform", then it will raise an error. We can either check compatibility before saving the data model, or during loading.

**Comment by djs0109** [comment]
@djs0109 Provide an example data model to define and show the error

**Comment by djs0109** [comment]
### Example json schema for a room:
```json
{
    "type": "object",
    "title": "HotelRoom",
    "properties": {
        "co2": {
            "anyOf": [
                {
                    "type": "number"
                },
                {
                    "type": "null"
                }
            ],
            "title": "Co2",
            "default": 0
        },
        "name": {
            "type": "string",
            "title": "Name",
            "default": null
        },
        "hasLocation": {
            "type": "string",
            "title": "Haslocation",
            "default": null
        },
        "temperature": {
            "anyOf": [
                {
                    "type": "number"
                },
                {
                    "type": "null"
                }
            ],
            "title": "Temperature",
            "default": 0
        }
    }
}
```

### Error report
```python
Traceback (most recent call last):
  ...
  File "D:\Git\n5geh.tools.entirety\app\Entirety\utils\parser.py", line 60, in parser
    schema_parser.parse_schema(schema=path, model_class=NormalizedModel)
  File "D:\Git\n5geh.tools.entirety\app\Entirety\src\jsonschemaparser\jsonschemaparser\parser.py", line 110, in parse_schema
    model = model_class.with_id_from_schema(schema_location=schema,
  File "D:\Git\n5geh.tools.entirety\app\Entirety\src\jsonschemaparser\jsonschemaparser\models\base.py", line 158, in with_id_from_schema
    identifier=Identifier(schema['$id']))
KeyError: '$id'
```

### Expected behavior
Error handling with the message: "The provided model is not compatible with FIWARE, probably `id` and `type` are missing."
